Repository clog-depromeet/clog-iOS, pull requests merged in 2025-02, with the labels that each got.

#8 Feature/make file
  Sample/Makefile
  Sample/graph.png
Labels: 📋 Documentation

#12 [Fix] make 명령 오류 해결
  Cllog/Script/addNewDomain.sh
  Cllog/Script/addNewFeature.sh
Labels: 🐞 BugFix

#11 [Feature] SpaceX Swift6 대응 ThreadSafe 작업
  Cllog/Makefile
  Cllog/Projects/AppModule/Sample/Project.swift
  Cllog/Projects/AppModule/SpaceX/Sources/SpaceX.swift
  Cllog/Projects/AppModule/Starlink/Project.swift
  Cllog/Projects/AppModule/Starlink/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Cllog/Projects/AppModule/Starlink/Resources/Assets.xcassets/Contents.json
  Cllog/Projects/AppModule/Starlink/Sources/.gitkeep
  Cllog/Projects/AppModule/Starlink/Sources/Configure/Configure.swift
  Cllog/Projects/AppModule/Starlink/Sources/Error/Error.swift
  Cllog/Projects/AppModule/Starlink/Sources/Error/ErrorInfo.swift
  Cllog/Projects/AppModule/Starlink/Sources/Headers/Header.swift
  Cllog/Projects/AppModule/Starlink/Sources/Interceptor/Interceptor.swift
  Cllog/Projects/AppModule/Starlink/Sources/Lock/NetworkerRWLock.swift
  Cllog/Projects/AppModule/Starlink/Sources/Lock/SafeDictionary.swift
  Cllog/Projects/AppModule/Starlink/Sources/Method/Method.swift
  Cllog/Projects/AppModule/Starlink/Sources/Request/Request.Response.swift
  Cllog/Projects/AppModule/Starlink/Sources/Request/Request.swift
  Cllog/Projects/AppModule/Starlink/Sources/Response/Response.swift
  Cllog/Projects/AppModule/Starlink/Sources/Session/Session.swift
  Cllog/Projects/AppModule/Starlink/Sources/Starlink.swift
  Cllog/Projects/AppModule/Starlink/Sources/Tracking/SafeTrackers.swift
  Cllog/Projects/AppModule/Starlink/Sources/Tracking/Tracking.swift
  Cllog/Projects/AppModule/Starlink/Tests/Sources/SampleApp.swift
  Cllog/Projects/AppModule/Starlink/Tests/Sources/SpaceX.swift
  Cllog/Projects/CllogService/Data/Networker/Project.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Sample.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
  Cllog/graph.png
Labels: 🛠️ Refactoring

#15 [DesiginKit] 네이밍 변경 -> ClLogUI
  Cllog/Projects/AppModule/Sample/Sources/SampleApp.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Project.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_background.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Bundle.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/ClLogUI.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Color.swift
  Cllog/graph.png
Labels: ✨ Feature

#18 [SPS-63] Match 인증서 작업
  .DS_Store
  .gitignore
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/AppConfiguration.swift
  Cllog/xcconfigs/Base/Projects/Project-Develop.xcconfig
  Cllog/xcconfigs/Base/Projects/Project-Production.xcconfig
  fastlane/Matchfile
  fastlane/api_key.json
Labels: ✨ Feature

#19 [feat] Console 추가
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogPhase.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogWindow.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
  Cllog/Projects/AppModule/Starlink/Project.swift
  Cllog/Projects/AppModule/Starlink/Sources/Configure/Configure.swift
  Cllog/Projects/AppModule/Starlink/Sources/ConsoleWIndow/ConsoleWIndow.swift
  Cllog/Projects/AppModule/Starlink/Sources/Delegate/StarlinkDelegate.swift
  Cllog/Projects/AppModule/Starlink/Sources/Interceptor/Interceptor.swift
  Cllog/Projects/AppModule/Starlink/Sources/Request/Request.Response.swift
  Cllog/Projects/AppModule/Starlink/Sources/Session/Session.swift
  Cllog/Projects/AppModule/Starlink/Sources/Starlink.swift
  Cllog/Projects/AppModule/Starlink/Sources/Tracking/Tracking.swift
  Cllog/Tuist/Package.resolved
  Cllog/Tuist/Package.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
Labels: ✨ Feature

#20 [SPS-67] 파이어페이스 연동
  Cllog/Projects/AppModule/Sample/Resources/GoogleService-Info.plist
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/CllogService/CoreKit/Core/Project.swift
  Cllog/Tuist/Package.resolved
  Cllog/Tuist/Package.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
Labels: ✨ Feature

#21 [feat] DesignKit Color 추가
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_background.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_dim.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray10.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray100.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray200.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray300.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray400.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray50.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray500.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray600.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray700.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray800.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray900.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_primary.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_white.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Color.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Sample.swift
Labels: ✨ Feature

#23 [Feat] 로그인 임시 View
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/appleLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/appleLogo.imageset/Shape.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/clogLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/clogLogo.imageset/logo.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/kakaoLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/kakaoLogo.imageset/Logo kakao.png
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/Sample.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Template/Project+Template.swift
Labels: ✨ Feature

#22 [Feat] 로그인 피쳐모듈 및 Domain 모듈 생성
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Project.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/appleLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/appleLogo.imageset/Shape.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/clogLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/clogLogo.imageset/logo.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/kakaoLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/kakaoLogo.imageset/Logo kakao.png
  Cllog/Projects/CllogService/Domains/Domain/Project.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Project.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Sample.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Project.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Tuist/Package.resolved
  Cllog/Tuist/Package.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Template/Project+Template.swift
  Cllog/xcconfigs/Base/Projects/Project-Develop.xcconfig
  Cllog/xcconfigs/Base/Projects/Project-Production.xcconfig
Labels: ✨ Feature

#25 Feature/sps 53/login
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Project.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/appleLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/appleLogo.imageset/Shape.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/clogLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/clogLogo.imageset/logo.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/kakaoLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/kakaoLogo.imageset/Logo kakao.png
  Cllog/Projects/CllogService/Domains/Domain/Project.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Project.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Sample.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Project.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Tuist/Package.resolved
  Cllog/Tuist/Package.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Template/Project+Template.swift
  Cllog/xcconfigs/Base/Projects/Project-Develop.xcconfig
  Cllog/xcconfigs/Base/Projects/Project-Production.xcconfig
Labels: ✨ Feature

#26 [feat] Firebase SPM 전환
  Cllog/.package.resolved
  Cllog/Projects/AppModule/Sample/Project.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/CllogService/CoreKit/Core/Project.swift
  Cllog/Tuist/Package.resolved
  Cllog/Tuist/Package.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Template/Project+Template.swift
Labels: 🐞 BugFix

#28 [SPS-72] 디자인 시스템 폰트, 컬러 작업
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogPhase.swift
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_background.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_dim.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray10.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray100.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray200.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray300.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray400.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray50.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray500.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray600.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray700.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray800.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray900.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_primary.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_white.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-Black.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-Bold.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-ExtraBold.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-ExtraLight.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-Light.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-Medium.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-Regular.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-SemiBold.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Font/Pretendard-Thin.ttf
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/ClLogLabel.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Color.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Bundle.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/ClLogUI.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Color.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/FontModel.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Fonts.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Modifire/Text+Modifire.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Sample.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/XCConfig.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Scheme+.swift
  Cllog/xcconfigs/Base/Projects/Project-Dev.xcconfig
  Cllog/xcconfigs/Base/Projects/Project-Prod.xcconfig
Labels: ✨ Feature

#27 [SPS-74] DI 모듈 개발
  Cllog/Projects/AppModule/Sample/Project.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogPhase.swift
  Cllog/Projects/AppModule/Sample/Sources/DI/ClLogDI.swift
  Cllog/Projects/AppModule/Sample/Sources/Log/ClLogger.swift
  Cllog/Projects/CllogService/Modules/ThirdPartyLibrary/Project.swift
  Cllog/Tuist/Package.resolved
  Cllog/Tuist/Package.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
  Cllog/graph.png
Labels: ✨ Feature

#30 [SPS-76] 디자인 시스템 General 버튼 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/GeneralButton.swift
Labels: ✨ Feature

#29 [SPS-75] [iOS] ClLogFont DI
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Fonts.swift
Labels: 🛠️ Refactoring
