Repository clog-depromeet/clog-iOS, pull requests merged in 2025-03, with the labels that each got.

#33 [SPS-65] 초기 화면 세팅
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/Feature/HomeFeature.swift
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/View/HomeView.swift
  Cllog/Projects/AppModule/Sample/Sources/Service/Home/View/HomeViewController.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Project.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/CaptureFeature.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/CaptureView.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
  Cllog/Projects/CllogService/Features/MainFeature/Sources/MainFeature.swift
  Cllog/Projects/CllogService/Features/MainFeature/Sources/MainView.swift
  Cllog/Projects/CllogService/Features/MainFeature/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#34 [SPS-82] 레코딩 버튼 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recodeButton.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recodeButton.imageset/recode_button.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recordingButton.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recordingButton.imageset/recording_button.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/RecodingButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/ClLogUI.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
Labels: ✨ Feature

#35 [SPS-77] UI Component - Chip & ETC 개발
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icn_close.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icn_close.imageset/icn_close.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icon_down.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icon_down.imageset/icon_down.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/x.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/x.imageset/x.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_complete.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_fail.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/CompleteOrFailChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/LevelChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/TitleWithImageChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ReportVideoImageView.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Color.swift
Labels: ✨ Feature

#37 [SPS-84] [iOS] 네트워크 개발 - Encodable하게 받게 수정
  Cllog/Projects/AppModule/Starlink/Sources/Error/Error.swift
  Cllog/Projects/AppModule/Starlink/Sources/Lock/SafeDictionary.swift
  Cllog/Projects/AppModule/Starlink/Sources/Request/Request.Response.swift
  Cllog/Projects/AppModule/Starlink/Sources/Starlink.swift
Labels: 🐞 BugFix, ✨ Feature, 🛠️ Refactoring

#36 [SPS-83] 카메라 버튼 디자인 적용
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/appleLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/appleLogo.imageset/Shape.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/clogLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/clogLogo.imageset/logo.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/kakaoLogo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Logo/kakaoLogo.imageset/Logo kakao.png
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/common/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/common/recodeButton.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/common/recodeButton.imageset/recode_button.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/common/recordingButton.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/common/recordingButton.imageset/recording_button.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green100.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green200.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green300.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green400.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green500.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green600.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green700.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green800.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_green900.colorset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/CameraButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/DropdownButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/FolderButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/NextProblemButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/RecodingButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/StampButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Color.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
Labels: ✨ Feature

#40 [SPS-53] 로그인 리펙토링
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogPhase.swift
  Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
  Cllog/Projects/CllogService/Data/Data/Sources/API/APIService.swift
  Cllog/Projects/CllogService/Data/Data/Sources/API/LoginAPI.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/AppleLoginRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/KakaoLoginReqeustDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/AuthTokenDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/BaseResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Local/TokenDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/AuthDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultLoginRepository.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Storage/AppData.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Storage/UserDefaultWrapper.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/EndpointType.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/ParameterType.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Provider/AuthProvider.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Provider/Provider.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Provider/UnAuthProvider.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Sample.swift
  Cllog/Projects/CllogService/Data/Starlink/Project.swift
  Cllog/Projects/CllogService/Data/Starlink/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Cllog/Projects/CllogService/Data/Starlink/Resources/Assets.xcassets/Contents.json
  Cllog/Projects/CllogService/Data/Starlink/Sources/.gitkeep
  Cllog/Projects/CllogService/Data/Starlink/Sources/Configure/Configure.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/ConsoleWIndow/ConsoleWIndow.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Delegate/StarlinkDelegate.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Error/Error.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Error/ErrorInfo.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Headers/Header.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Interceptor/Interceptor.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Lock/NetworkerRWLock.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Lock/SafeDictionary.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Method/Method.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Request/Request.Response.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Request/Request.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Response/Response.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Session/Session.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Starlink.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Tracking/SafeTrackers.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Tracking/Tracking.swift
  Cllog/Projects/CllogService/Data/Starlink/Tests/Sources/SampleApp.swift
  Cllog/Projects/CllogService/Data/Starlink/Tests/Sources/SpaceX.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeatureAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogDI.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Log/ClLogger.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/Feature/HomeFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeViewController.swift
  Cllog/Projects/CllogService/Service/Sources/Sample.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Path+.swift
Labels: ✨ Feature

#41 [SPS-90] UI Component - VideoTimeChip & Tooltip 개발
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/CompleteOrFailChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/LevelChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/TitleWithImageChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/VideoTimeChip.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/Tooltip.swift
Labels: ✨ Feature

#44 [SPS-106] 디자인 시스템 바텀시트 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/BottomSheet.swift
Labels: ✨ Feature

#45 [SPS-110] 다이얼로그 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/GeneralButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Dialog/Dialog+Extension.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Dialog/DialogButtonType.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Dialog/DialogModel.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Dialog/DialogModifier.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Dialog/DialogView.swift
Labels: ✨ Feature

#51 [SPS-111] TokenInterceptor 생성
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/AuthTokenDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Local/TokenDataSource.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Interceptor/TokenInterceptor.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Model/TokenDTO.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Provider/AuthProvider.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Provider/Provider.swift
Labels: ✨ Feature

#54 [SPS-86] 촬영 기능에 접근, 카메라 접근 권한
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/close.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/close.imageset/x.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/VideoDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/CaptureRecordRepositry.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Provider/Provider.swift
  Cllog/Projects/CllogService/Domains/CaptureDomain/Sources/Repository/CaptureRepository.swift
  Cllog/Projects/CllogService/Domains/CaptureDomain/Sources/UseCase/CapturePermissionUseCase.swift
  Cllog/Projects/CllogService/Domains/CaptureDomain/Sources/UseCase/CaptureUseCase.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarView.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Capture/CaptureView.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/DI/CaptureFeatureAssembly.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Record/ClLogSessionUIView.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Record/ClLogSessionView.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Record/ClLogSessionViewModel.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Record/RecordFeature.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Record/RecordView.swift
  Cllog/Projects/CllogService/Features/CaptureFeature/Sources/Record/UIVideoPlay.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/Feature/HomeFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
Labels: ✨ Feature

#61 fix. 텍스트 필드 수정
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/ClLogTextInput.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/TextInputConfiguration.swift
Labels: 🐞 BugFix

#60 Feature/sps 57 카메라촬영/sps 133
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/VideoRecordRepositry.swift
  Cllog/Projects/CllogService/Domains/CaptureDomain/Sources/UseCase/CaptureUseCase.swift
  Cllog/Projects/CllogService/Domains/Domain/Project.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Project.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/CaptureRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Sample.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/VideoPermissionUseCase.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/VideoUseCase.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Project.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/DI/VideoFeatureAssembly.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/ClLogSessionUIView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/ClLogSessionView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/ClLogSessionViewModel.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/UIVideoPlay.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/Feature/HomeFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#62 [SPS-112] 영상 편집 > 하단 편집 영역 UI 개발
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/playSmall.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/playSmall.imageset/playSmall.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/redo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/redo.imageset/redo.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/stopSmall.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/stopSmall.imageset/stopSmall.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/undo.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/Edit/undo.imageset/undo.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/close_circle.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/close_circle.imageset/x.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/stampSmall.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/stampSmall.imageset/stampSmall.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
  Cllog/Projects/CllogService/Features/EditFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/EditFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/EditFeature/Project.swift
  Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/DragEditView.swift
  Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/ThumbnailsView.swift
  Cllog/Projects/CllogService/Features/EditFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/EditFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#64 [SPS-137] 캘린더 메인 API 조회 및 테스트 코드 작성
  Cllog/Projects/CllogService/CoreKit/DesignKit/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Demo/Sources/App.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Project.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/YearMonthRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/DateResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/DayResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/ProblemResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/StoryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/CalendarDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultCalendarRepository.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Project.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarDate.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbCalendar.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbDay.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbProblem.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbStroy.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Repository/CalendarRepository.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/UseCase/FetchCalendarUseCase.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/UseCase/FutureMonthCheckerUseCase.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Tests/Sources/FetchCalendarTest.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Tests/Sources/FutureMonthCheckerTest.swift
  Cllog/Projects/CllogService/Domains/Domain/Project.swift
  Cllog/Projects/CllogService/Domains/Domain/Sources/Entity/ClimbeDays.swift
  Cllog/Projects/CllogService/Domains/SampleDomain/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/DayView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Main/CalendarMainFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Main/CalendarMainView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift
  Cllog/Projects/CllogService/Modules/Shared/Sources/Extension/Date+.swift
  Cllog/Projects/CllogService/Modules/Shared/Sources/Extension/Int+.swift
  Cllog/Projects/CllogService/Modules/Shared/Sources/Extension/String+.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/AppConfiguration.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Scheme+.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Template/ModuleType.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Template/Project+Template.swift
  Cllog/graph.png
Labels: ✨ Feature

#67 [SPS-133]
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Progress/RecordProgressBar.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Color.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Modifire/DebugFrame.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/VideoRecordRepositry.swift
  Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/LogConsoleUseCase.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/CaptureRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/VideoPermissionUseCase.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/VideoUseCase.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Features/EditFeature/Demo/Resources/Empty.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
  Cllog/Projects/CllogService/Features/MainFeature/Sources/MainFeature.swift
  Cllog/Projects/CllogService/Features/MainFeature/Sources/MainFeatureAssembly.swift
  Cllog/Projects/CllogService/Features/MainFeature/Sources/MainView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/DI/VideoFeatureAssembly.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Session/ClLogSessionUIView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Session/ClLogSessionView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Session/ClLogSessionViewModel.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/UIVideoPlay.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Video/VideoPlayView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Video/VideoPlayViewModel.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoSession/VideoPreview.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoSession/VideoPreviewViewModel.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoSession/VideoSession.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/AutoLogin/AutoLoginFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/AutoLogin/AutoLoginView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/DI/HomeFeatureAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/Feature/HomeFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
Labels: ✨ Feature

#65 [SPS-140] 캘린더 바텀시트 Story 화면 개발
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/DropdownButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Extension/Color+Extension.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarDate.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbDay.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbProblem.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbStroy.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/ClimbingCard.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/DayBottomSheet/DayBottomSheet.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Main/CalendarMainFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift
  Cllog/Projects/CllogService/Features/FolderTabFeature/Sources/Presentaition/FolderTabFeature.swift
  Cllog/Projects/CllogService/Modules/Shared/Sources/Extension/Int+.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#70 [SPS-143] 캘린더 디테일 화면 push 작업
  Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
  Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/FolderFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeViewController.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
Labels: ✨ Feature

#71 [SPS-142] 캘린더 상세 화면 Story 조회 API 연동 작업
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Calendar/YearMonthRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarDayResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarProblemResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarStoryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarSummaryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/DateResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryAttemptResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryProblemResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryStampResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryVideoResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Summary/StorySummaryProblemResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Summary/StorySummaryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/CalendarDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultStoryRepository.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarDay.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarProblem.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarStory.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarSummary.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/ClimbCalendar.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Repository/CalendarRepository.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/UseCase/FetchCalendarUseCase.swift
  Cllog/Projects/CllogService/Domains/Domain/Project.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Project.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/Story.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryAttempt.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryAttemptStatus.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryProblem.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryStamp.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryVideo.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Summary/StorySummary.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Summary/StorySummaryProblem.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Repository/StoryRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/FetchStoryUseCase.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/ClimbingCard.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/DayView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/DayBottomSheet/DayBottomSheet.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Main/CalendarMainFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
Labels: ✨ Feature

#75 [SPS-154] 화면 전환 Coordinator 작업
  Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Coordinator/BaseNavigationController.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Coordinator/Coordiantor.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeViewController.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainCoordinator.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/AutoLogin/AutoLoginFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/AutoLogin/AutoLoginView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/DI/HomeFeatureAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootView.swift
Labels: ✨ Feature

#74 [SPS-144] 캘린더 상세 페이지 UI 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Summary/StorySummaryProblemResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Summary/StorySummaryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/Story.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryAttempt.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryAttemptStatus.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryProblem.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryStamp.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryVideo.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Summary/StorySummary.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Summary/StorySummaryProblem.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Main/CalendarMainFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Stories/StoriesFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Stories/StoriesView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
Labels: ✨ Feature

#79 [SPS-154] 화면 이동 작업 리팩토링
  Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
  Cllog/Projects/CllogService/Features/FolderTabFeature/Sources/Presentaition/FolderTabView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Coordinator/BaseNavigationController.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Coordinator/Coordiantor.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainCoordinator.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/EnableBackSwipeModifier.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/Path.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift
Labels: 🛠️ Refactoring

#82 [SPS-156] 리포트, 설정 화면 작업 및 이동 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/setting.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/setting.imageset/setting.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/AppBar/AppBar.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Project.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Sources/Presentation/ReportFeature.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Sources/Presentation/ReportView.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Project.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/SettingFeature.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/SettingView.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/Path.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#85 [SPS-156] 설정 UI 작업
  Cllog/Projects/CllogService/Features/SettingFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Component/SettingRow.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingView.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Profile/ProfileFeature.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Profile/ProfileView.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/SettingView.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/UIModel/SettingItemType.swift
Labels: ✨ Feature

#86 [SPS-102] 로그아웃 기능 개발
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/BaseResponse/BaseResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Local/TokenDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultLoginRepository.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultLogoutRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Project.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/LoginRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/LogoutRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Login/LoginUseCase.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Logout/LogoutUseCase.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Domains/Domain/Project.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Depenency/LoginUseCaseKey.swift
  Cllog/Projects/CllogService/Domains/LoginDomain/Sources/UseCase/LoginUseCase.swift
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
Labels: ✨ Feature

#89 [SPS-168] 앱아이콘 변경, 스플레시 화면 이동 작업
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-20@2x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-20@2x~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-20@3x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-20~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-29.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-29@2x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-29@2x~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-29@3x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-29~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-40@2x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-40@2x~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-40@3x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-40~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-60@2x~car.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-60@3x~car.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5@2x~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon@2x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon@2x~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon@3x.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon~ipad.png
  Cllog/Projects/AppModule/Sample/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Color/Color.xcassets/clLogUI_gray900.colorset/Contents.json
  Cllog/Projects/CllogService/Features/SplashFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Project.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashFeature.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashView.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/AutoLogin/AutoLoginFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/AutoLogin/AutoLoginView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#90 [SPS-103] 회원 탈퇴
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultTokenRepository.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefualtWithdrawRepository.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Model/TokenDTO.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/TokenRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/WithdrawRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/LoginTypeFetcher/LoginTypeFetcherUseCase.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Logout/LogoutUseCase.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Withdraw/WithdrawUseCase.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
Labels: ✨ Feature

#91 [SPS-170] 자동 로그인 적용
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultTokenRepository.swift
  Cllog/Projects/CllogService/Data/Networker/Sources/Model/TokenDTO.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/TokenRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/LoginTypeFetcher/LoginTypeFetcherUseCase.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/ValidateUserSession/ValidateUserSessionUseCase.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashFeature.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
Labels: ✨ Feature

#92 [SPS-169] 개인정보 처리 방침, 서비스 이용약관 WebView 작업
  Cllog/Projects/CllogService/CoreKit/Core/Sources/View/Router/EnableBackSwipeModifier.swift
  Cllog/Projects/CllogService/CoreKit/Core/Sources/View/WebView/WebView.swift
  Cllog/Projects/CllogService/CoreKit/Core/Sources/View/WebView/WebViewFeature.swift
  Cllog/Projects/CllogService/CoreKit/Tests/Sources/.gitkeep
  Cllog/Projects/CllogService/CoreKit/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingView.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/UIModel/SettingItemType.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/Path.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift
Labels: ✨ Feature

#94 [SPS-103] 애플 회원탈퇴 기능 적용
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Account/AppleLoginRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Account/AppleWithdrawCodeRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Account/KakaoLoginReqeustDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefualtWithdrawRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/WithdrawRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Withdraw/WithdrawUseCase.swift
  Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
Labels: ✨ Feature

#96 [SPS-157] 스토리 메모 수정 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/delete.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/delete.imageset/icn_delete.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/edit.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/icons/edit.imageset/icn_edit.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/ClLogTextInput.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/TextInputConfiguration.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/CragBottomSheet.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Memo/EditMemoRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultEditMemoRepository.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Method/Method.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Repository/EditMemoRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/EditMemoUseCase.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/Component/MoreItemRow.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/UIModel/MoreItem.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift
  Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Folder/FolderView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Labels: ✨ Feature

#99 [SPS-158] 캘린더 스토리 삭제 작업
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultDeleteStoryRepository.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultStoryRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Repository/DeleteStoryRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/DeleteStoryUseCase.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
Labels: ✨ Feature

#97 [SPS-162] 영상 편집 - 툴팁 관리
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/Tooltip.swift
  Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/EditFeatureTooltipManager.swift
  Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditView.swift
Labels: ✨ Feature

#102 [SPS-152] 온보딩 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding1.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding1.imageset/splash1.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding2.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding2.imageset/splash2.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding3.imageset/Contents.json
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding3.imageset/splash3.svg
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Project.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Sources/Presentation/OnboardingFeature.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Sources/Presentation/OnboardingView.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Sources/Presentation/PageView.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashFeature.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/UserDefault/SplashDataManager.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#105 [SPS-186] 동영상 촬영 후 편집화면 이동
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift
Labels: ✨ Feature

#107 [SPS-188] 영상 촬영 기록 저장
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Story/AttemptRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Story/StoryRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarStoryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Story/SaveStoryResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultSaveStoryRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Story/AttemptRequest.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Story/SavedStory.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Story/StoryRequest.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Video/VideoUploadModel.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Video/Videothumbnails.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/SaveStoryRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Sample.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/SaveStory/SaveStoryUseCase.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/Video/VideoPermissionUseCase.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/Video/VideoUseCase.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedView.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Labels: ✨ Feature

#110 [SPS-191] 사진첩 저장 기능
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/VideoRecordRepositry.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/CaptureRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/Video/VideoUseCase.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift
Labels: ✨ Feature

#111 [SPS-192] 영상 촬영 UI 작업
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/FolderButton.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/NextProblemButton.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Story/SavedStory.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recording/RecordingFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recording/RecordingView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/UserDefault/VideoDataManager.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
Labels: ✨ Feature

#117 [SPS-200] 권한 요청 시점 변경 및 추적 권한 추가
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift
Labels: ✨ Feature

#119 [kickout] 킥아웃 기능 구현
  Cllog/Projects/AppModule/Sample/Sources/Core/ClLogWindow.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultTokenRepository.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Error/Error.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Error/ErrorInfo.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/Request/Request.Response.swift
  Cllog/Projects/CllogService/Data/Starlink/Sources/SessionError/SessionErrorHandler.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/TokenRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/LoginTypeFetcher/LoginTypeFetcherUseCase.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Demo/Sources/AppDelegate.swift
Labels: ✨ Feature

#121 [SPS-189] 시도 저장
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Attempt/AttemptRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/AttemptDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultSaveAttemptRepository.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultSaveStoryRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryAttempt.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Story/AttemptRequest.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/SaveAttemptRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/SaveAttempt/SaveAttemptUseCase.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/UserDefault/VideoDataManager.swift
  Cllog/Projects/CllogService/Modules/Shared/Sources/Entity/AttemptStatus.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Labels: ✨ Feature

#131 [썸네일] 사용하지 않는 코드 삭제 및 name 인터페이스 삭제
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Video/VideoUploadResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/VideoDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/VideoRecordRepositry.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/CaptureRepository.swift
  Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/Video/VideoUseCase.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Labels: ✨ Feature

#134 [SPS-235] 최초 가입시 닉네임 설정
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/ClLogTextInput.swift
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/TextInputConfiguration.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Account/UserNameRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Account/UserResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultAccountRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Entity/User.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/AccountRepository.swift
  Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Account/AccountUseCase.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Demo/Sources/AppDelegate.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Project.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Sources/Presentation/NickNameFeature.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Sources/Presentation/NickNameView.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Sources/UIModel/NickNameViewState.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/NickNameFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashFeature.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#133 [SPS-232][영상 편집] 좌측 트리밍 핸들과 playHead가 만나면 재생 안되는 이슈 수정
  Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift
Labels: 🐞 BugFix

#135 [SPS-233][영상 편집] 영상 구간 편집 안되는 이슈 수정
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Progress/PlayerProgressBar.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedPlayView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedPlayViewModel.swift
Labels: 🐞 BugFix

#136 [SPS-214] 총 운동 시간이 표시 되지 않는 버그 수정
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheet.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheetFeature.swift
Labels: 🐞 BugFix

#137 [SPS-221] 기록 저장 취소 버튼 위치 변경
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Labels: 🐞 BugFix

#138 [SPS-223] 리포트 뿌듯했던 도전 성공, 실패 Chip 제거
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift
  Cllog/Projects/CllogService/Features/ReportFeature/Sources/Presentation/ReportView.swift
Labels: 🐞 BugFix

#139 [SPS-231] 바텀시트 썸네일 출력되지 않는 현상 수정
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ReportVideoImageView.swift
Labels: 🐞 BugFix

#140 [SPS-208] 캘린더 관련 버그 수정
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarDayResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarStoryResponseDTO.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarDay.swift
  Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarStory.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/ClimbingCard.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/DayView.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/DayBottomSheet/DayBottomSheet.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
  Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift
Labels: 🐞 BugFix

#142 [SPS-218] 이용약관, 개인정보 웹 URL 변경
  Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
Labels: 🐞 BugFix

#143 [SPS-256] 온보딩 수정
  Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/OnBoarding/onBoarding1.imageset/splash1.svg
  Cllog/Projects/CllogService/Features/OnboardingFeature/Sources/Presentation/OnboardingView.swift
  Cllog/Projects/CllogService/Features/OnboardingFeature/Sources/Presentation/PageView.swift
Labels: 🐞 BugFix

#144 [SPS-243] 저장 연속 클릭되는 현상 수정
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeView.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
Labels: 🐞 BugFix

#146 [SPS-244] 난이도 변경 이슈 해결
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Story/ProblemRequestDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Problem/RegisterProblemResponseDTO.swift
  Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
  Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultProblemRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Repository/ProblemRepository.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/RegisterProblemUseCase.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/UserDefault/VideoDataManager.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
  Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift
Labels: ✨ Feature

#147 [kickout] upload api 호출시 킥아웃 로직 추가
  Cllog/Projects/CllogService/Data/Starlink/Sources/Request/Request.Response.swift
Labels: 🐞 BugFix

#153 [shared] 인스타그램 공유하기 기능 추가
  Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/SharedView/InstagramSharerView.swift
  Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
  Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptView.swift
Labels: ✨ Feature

#152 [SPS-254][영상 편집] 툴팁 외 화면 선택 시 안넘어감 수정
  Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditView.swift
Labels: 🐞 BugFix

#157 [SPS-230] 영상 촬영 최종 결과, 공유 기능 추가
  Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Summary/StorySummaryResponseDTO.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Summary/StorySummary.swift
  Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/FetchStoryUseCase.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Demo/Resources/Sample.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Demo/Sources/App.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Interface/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Project.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Sources/Presentation/CompletionReportFeature.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Sources/Presentation/CompletionReportView.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Test/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/CompletionReportFeature/Tests/Sources/Sample.swift
  Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
  Cllog/Projects/CllogService/Service/Project.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/Path.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
  Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift
  Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Labels: ✨ Feature

#149 [window] portrait
  Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Labels: ✨ Feature
